project:
  type: website
  output-dir: _site

website:
  title: "Traducciones"
  site-url: "https://lazlowicz.github.io/traducciones/"
  repo-url: "https://github.com/lazlowicz/traducciones"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: proyectos/index.qmd
        text: Proyectos
  sidebar:
    - title: "Proyectos"
      style: "docked"
      contents:
        - proyectos/index.qmd
        - section: "The Compleat Strategist"
          contents:
            - proyectos/the-compleat-strategist/index.qmd
        - section: "The Society of Mind"
          contents:
            - proyectos/the-society-of-mind/index.qmd
        - section: "How to Solve It"
          contents:
            - proyectos/how-to-solve-it/index.qmd
        - section: "Everything and More"
          contents:
            - proyectos/everything-and-more/index.qmd

lang: es-AR

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.scss
    toc: true
    toc-depth: 3
    code-copy: true
    anchor-sections: true
    reference-location: margin
    citation-location: margin
    cap-location: margin
    grid:
      sidebar-width: 250px
      body-width: 760px
      margin-width: 280px
      gutter-width: 1.5rem

execute:
  freeze: auto
